### PR TITLE
Fixed missing include in header

### PR DESCRIPTION
**Pull request by arteniioleg**
and removed prints from `render()`

### CODE REVIEW

**Comment by arteniioleg** [comment]
P.S. All that commented code, `cout` debugs and `new` gives the impression that the library is a draft. I hope it doesn't leak.

P.P.S. Have you considered switching to smart pointers?

**Comment by hughperkins** [comment]
> P.S. All that commented code, cout debugs and new gives the impression that the library is a draft. I hope it doesn't leak.
>.P.S. Have you considered switching to smart pointers?

Please feel free to hack it around a bit, clean it up, and so on :)

**Comment by arteniioleg** [comment]
Ok Thanks

Merge?

**Comment by hughperkins** [comment]
Oh heh! I hadnt noticed you had submitted 2 PRs. You are too fast :D Thanks! :)

**Pull request merged**
